definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:catalog:
      jcr:primaryType: hst:catalog
      /gogreen-catalog:
        jcr:primaryType: hst:containeritempackage
        /featured-products:
          jcr:primaryType: hst:containeritemcomponent
          hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsListPickerComponent
          hst:label: Featured Products
          hst:template: featured-products
          hst:xtype: hst.item
