definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:sitemap:
      jcr:primaryType: hst:sitemap
      /root:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/homepage
        hst:refId: root
      /_any_:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/pagenotfound
      /pagenotfound:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/pagenotfound
        hst:refId: pagenotfound
      /news:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/newslist
        hst:relativecontentpath: newsfacets
        /_any_.html:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/newspage
          hst:relativecontentpath: news/${1}
        /_any_:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/newslist
          hst:relativecontentpath: ${parent}/${1}
      /content:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/contentlist
        hst:relativecontentpath: content
        /_any_.html:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/contentpage
          hst:relativecontentpath: ${parent}/${1}
        /_any_:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/contentlist
          hst:relativecontentpath: ${parent}/${1}
      /search:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/search
        hst:refId: search
      /products:
        jcr:primaryType: hst:sitemapitem
        hst:componentconfigurationid: hst:pages/productslist
        hst:relativecontentpath: products
        /_any_.html:
          jcr:primaryType: hst:sitemapitem
          hst:componentconfigurationid: hst:pages/productpage
          hst:relativecontentpath: ${parent}/${1}
