definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:pages/contentpage:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/twocolumns
      /main:
        jcr:primaryType: hst:component
        /left:
          jcr:primaryType: hst:containercomponentreference
          hst:referencecomponent: contentpage/main/left
        /right:
          jcr:primaryType: hst:component
          hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
          hst:parameternames: [menu]
          hst:parametervalues: [main]
          hst:template: twocolumns-right-menu
