definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:pages/search:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/base
      /main:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsSearchComponent
        hst:template: search-main
